import { expect, test } from "@playwright/test";

test("캐릭터 영상·모션 정지와 복귀 동선은 주행이나 업로드 없이 동작한다", async ({ page }) => {
  test.setTimeout(60000);
  const writes: string[] = [], errors: string[] = [];
  page.on("request", r => { if (r.method() === "POST") writes.push(r.url()); });
  page.on("pageerror", e => errors.push(e.message));
  await page.goto("/#experiment");
  const showcase = page.getByRole("figure", { name: "움직이는 미스터팍 캐릭터" });
  await showcase.scrollIntoViewIfNeeded();
  const video = showcase.locator("video");
  await expect(video).toBeVisible();
  await expect(showcase.locator("canvas")).toHaveCount(0);
  await expect(showcase.locator(".mascot-stage")).toHaveAttribute("data-animate", "true");
  await expect.poll(() => video.evaluate(el => (el as HTMLVideoElement).currentTime)).toBeGreaterThan(.1);
  await showcase.getByRole("button", { name: "캐릭터 영상 멈추기" }).click();
  await expect(showcase.locator(".mascot-stage")).toHaveAttribute("data-animate", "false");
  await expect.poll(() => video.evaluate(el => (el as HTMLVideoElement).paused)).toBe(true);
  await showcase.getByRole("button", { name: "캐릭터 영상 재생" }).click();
  await expect(showcase.locator(".mascot-stage")).toHaveAttribute("data-animate", "true");
  await page.getByText("화면 설정 · AI 모델 정보",{exact:true}).click();
  await page.getByRole("checkbox",{name:"화면 움직임 줄이기"}).check();
  await expect(showcase.locator(".mascot-stage")).toHaveAttribute("data-animate", "false");
  await expect(page.locator(".continuous-backdrop")).toHaveCount(1);
  await expect(page.locator("#experiment .signal-field svg")).toBeHidden();
  await page.getByRole("link", { name: "플레이그라운드", exact: true }).click();
  await expect(page.getByRole("button", { name: "직접 운전하기", exact: true })).toBeVisible();
  await expect.poll(() => video.evaluate(el => (el as HTMLVideoElement).paused)).toBe(true);
  await page.getByRole("link", { name: "우리의 실험", exact: true }).click();
  await showcase.scrollIntoViewIfNeeded();
  await expect(video).toBeVisible();
  await expect(showcase.getByText("BRAND FILM / 01", { exact: true })).toBeVisible();
  expect(writes).toEqual([]);
  expect(errors).toEqual([]);
});

test("소개 구간의 관전 버튼도 첫 기록 선택을 거치며 서버 불가 이유를 표시한다", async ({ page }) => {
  test.setTimeout(60000);
  await page.addInitScript(() => { localStorage.clear(); localStorage.setItem("parkside-quality", "low"); });
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.route("**/api/collection", r => r.fulfill({ json: { enabled: false } }));
  await page.goto("/#experiment");
  await page.getByRole("button", { name: "미스터팍 주행 보기", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: /어떻게 남길까요/ });
  await expect(dialog).toBeVisible();
  await expect(dialog.getByText("현재 이용 불가", { exact: true })).toBeVisible();
  await expect(dialog.getByLabel("학습용 기록 전송에 동의하고 켜기")).toBeDisabled();
  await expect(dialog.getByRole("button", { name: "선택하고 시작하기" })).toBeDisabled();
  await dialog.getByLabel("이 브라우저에 주행 기록 보관", { exact: true }).check();
  await expect(dialog.getByRole("button", { name: "선택하고 시작하기" })).toBeEnabled();
  await dialog.getByRole("button", { name: "기록 없이 시작", exact: true }).click();
  await expect(page.locator(".mission-hud")).toContainText("LEARNED LIVE", { timeout: 30000 });
  expect(await page.evaluate(() => localStorage.getItem("parkside-record-locally"))).toBe("off");
});

for (const width of [390, 1440]) test(`하단 ${width}px 레이아웃·모션 감소·3D 위 스크롤`, async ({ page }) => {
  test.setTimeout(60000);
  await page.setViewportSize({ width, height: 900 });
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/#experiment");
  const showcase = page.getByRole("figure", { name: "움직이는 미스터팍 캐릭터" });
  await showcase.scrollIntoViewIfNeeded();
  await expect(showcase.locator(".mascot-poster")).toBeVisible();
  await expect(showcase.locator(".mascot-stage")).toHaveAttribute("data-animate", "false");
  await expect(showcase.getByRole("button", { name: "캐릭터 영상 재생" })).toBeDisabled();
  await expect(showcase.locator("video")).not.toHaveAttribute("src");
  await page.screenshot({ path: test.info().outputPath(`mascot-${width}.png`) });
  const lab = page.getByLabel("차량 기술 살펴보기");
  await lab.locator(".lab-render").scrollIntoViewIfNeeded();
  const canvas = lab.locator("canvas");
  await expect(canvas).toBeVisible();
  const box = (await canvas.boundingBox())!;
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  const scrollBefore = await page.evaluate(() => scrollY);
  await page.mouse.wheel(0, 180);
  await expect.poll(() => page.evaluate(() => scrollY)).toBeGreaterThan(scrollBefore + 80);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: test.info().outputPath(`lab-${width}.png`) });
});
